name: CI Build MacOS M1

on: [pull_request]

jobs:
  build-debug:
    runs-on: [m1]

    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      run: arch -arm64 brew install cmake

    - name: Configure CMake
      run: arch -arm64 cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: arch -arm64 cmake --build ${{github.workspace}}/build --config Debug

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Debug build
        path: ${{github.workspace}}/build/chia_plot

  build-release:
    runs-on: [m1]

    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      run: arch -arm64 brew install cmake

    - name: Configure CMake
      run: arch -arm64 cmake -B ${{github.workspace}}/build

    - name: Build
      run: arch -arm64 cmake --build ${{github.workspace}}/build --config Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Release build
        path: ${{github.workspace}}/build/chia_plot
